version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2804
      MYSQL_DATABASE: product_service
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  auth-service:
    build: ./project-express-authen
    container_name: auth-service
    restart: always
    env_file:
      - ./project-express-authen/.env.authen
    depends_on:
      - mongo
    ports:
      - "3001:3001"

  product-service:
    build: ./project-express-product
    container_name: product-service
    restart: always
    env_file:
      - ./project-express-product/.env.product
    depends_on:
      - mysql
    ports:
      - "3002:3002"

  upload-service:
    build: ./project-express-uploadfile
    container_name: upload-service
    restart: always
    env_file:
      - ./project-express-uploadfile/.env.uploadfile
    depends_on:
      - mongo
    ports:
      - "3003:3003"
    
  kong:
    build: ./gateway   
    container_name: kong-gateway
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./gateway/kong.yml:/usr/local/kong/declarative/kong.yml:ro
    depends_on:
      - auth-service
      - product-service
      - upload-service
    ports:
      - "8000:8000"  
      - "8001:8001"  

volumes:
  mongo_data:
  mysql_data:
